# Generated by Django 4.2.7 on 2025-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="business_logos/"),
        ),
        migrations.AddField(
            model_name="business",
            name="primary_color",
            field=models.CharField(default="#f97316", max_length=7),
        ),
        migrations.AddField(
            model_name="business",
            name="receipt_footer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="business",
            name="receipt_header",
            field=models.TextField(blank=True),
        ),
    ]
