# Generated by Django 4.2.7 on 2025-09-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_business_logo_business_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
