# Generated by Django 4.2.7 on 2025-09-04 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_business_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="created_at",
            new_name="registration_date",
        ),
        migrations.RenameField(
            model_name="business",
            old_name="trial_ends_at",
            new_name="trial_end_date",
        ),
        migrations.RemoveField(
            model_name="business",
            name="location",
        ),
        migrations.RemoveField(
            model_name="business",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="business",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="business",
            name="receipt_footer",
        ),
        migrations.RemoveField(
            model_name="business",
            name="receipt_header",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="business",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="business",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.business",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("cashier", "Cashier"),
                ],
                default="owner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_business",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
