# Generated by Django 4.2.7 on 2025-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_created_at_business_registration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
        ),
    ]
