# Generated by Django 4.2.7 on 2025-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="business_logos/"),
        ),
        migrations.AddField(
            model_name="business",
            name="primary_color",
            field=models.CharField(default="#3B82F6", max_length=7),
        ),
        migrations.AddField(
            model_name="business",
            name="secondary_color",
            field=models.CharField(default="#6B7280", max_length=7),
        ),
    ]
