name: supawave-backend
services:
  - name: web
    type: web
    build:
      type: buildpack
      buildpack: python
    run: gunicorn inventory_saas.wsgi:application --bind 0.0.0.0:$PORT
    ports:
      - port: 8000
        protocol: http
    env:
      - name: PORT
        value: "8000"
    health_check:
      http:
        path: /api/health/
        port: 8000