# Generated by Django 4.2.7 on 2025-09-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_business_logo_business_primary_color_and_more"),
        ("inventory", "0008_stocktake_stocktakeitem"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictivealert",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_alerts",
                to="accounts.business",
            ),
        ),
        migrations.AlterField(
            model_name="predictivealert",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_alerts",
                to="inventory.product",
            ),
        ),
    ]
