# Generated by Django 4.2.7 on 2025-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_product_barcode_product_max_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("barcode__isnull", False), models.Q(("barcode", ""), _negated=True)
                ),
                fields=("barcode", "business"),
                name="unique_barcode_per_business",
            ),
        ),
    ]
