# Generated by Django 4.2.7 on 2025-09-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_business_logo_business_primary_color_and_more"),
        ("inventory", "0006_convert_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "business")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("barcode", "business"), ("sku", "business")},
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("name", "business")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["business", "is_active"], name="inventory_p_busines_dc2763_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["business", "category"], name="inventory_p_busines_c24ca0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["barcode"], name="inventory_p_barcode_3a77e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="inventory_p_sku_f85905_idx"),
        ),
    ]
