# Generated by Django 4.2.7 on 2025-09-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
