# Generated by Django 4.2.7 on 2025-09-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_store_manager_user"),
        ("sales", "0003_fix_uuid_compatibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
