# Generated by Django 4.2.7 on 2025-09-08 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0006_business_logo_business_primary_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("region", models.CharField(default="Nigeria", max_length=100)),
                ("avg_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sample_size", models.IntegerField()),
                ("price_trend", models.CharField(default="stable", max_length=20)),
                ("demand_level", models.CharField(default="normal", max_length=20)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("product_name", "region")},
            },
        ),
        migrations.CreateModel(
            name="BusinessInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("pricing", "Pricing Recommendation"),
                            ("inventory", "Inventory Alert"),
                            ("demand", "Demand Forecast"),
                            ("competition", "Market Intelligence"),
                            ("opportunity", "Business Opportunity"),
                            ("warning", "Risk Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("action_required", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.8)),
                ("data_sources", models.JSONField(default=list)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AICoachSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("session_type", models.CharField(default="text", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.business",
                    ),
                ),
            ],
        ),
    ]
