# Generated by Django 4.2.7 on 2025-09-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_purchaseorder_salesvelocity_purchaseorderitem_and_more"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacelisting",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace_listings",
                to="inventory.product",
            ),
        ),
    ]
