# Generated by Django 4.2.7 on 2025-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_marketplacelisting_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacelisting",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
