# Generated by Django 4.2.7 on 2025-09-06 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["-created_at"]},
        ),
    ]
