# Generated by Django 4.2.7 on 2025-09-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0002_alter_store_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="manager_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_store",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
